import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'X',
  description: 'Generated by X',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className='max-w-screen-2xl mx-auto mt-5'>
          <Navbar></Navbar>

          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
