import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '@/context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'X',
  description: 'Generated by X',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ThemeProvider>
          <div className='max-w-screen-2xl mx-auto pt-5'>
            <Navbar></Navbar>

            <div className='flex flex-col min-h-screen justify-between'>
              <div className=''>
                {children}
              </div>
              <Footer></Footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
